[cohesive]
repo = "https://raw.githubusercontent.com/mcxross/cohesives/main/src/res/"
    [cohesive."primary"]
        enabled = []
        disabled = []
    [cohesive."secondary"]
        enabled = []
        disabled = []

[platform]
k = ["Mainnet", "Testnet", "Devnet"]
v = ["", "", ""]
    [platform."tertiary"]
        enabled = []
        disabled = []