[chain]
clusterKey = ["Mainnet", "Testnet", "Devnet"]
clusterValue = ["", "", ""]

[plugin]
    [plugin."primary"]
        enabled = []
        disabled = []
    [plugin."secondary"]
        enabled = []
        disabled = []
    [plugin."tertiary"]
        enabled = []
        disabled = []